spring:
  application:
    name: petshop
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://localhost:5432/petshop
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
